import mongoose from 'mongoose';

/**
 * AiInsight Model
 * Stores AI-generated business insights and recommendations.
 * Insights can be generated by Gemini API or produced from DB analytics.
 */
const aiInsightSchema = new mongoose.Schema(
  {
    restaurantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Restaurant',
    },
    type: {
      type: String,
      enum: [
        'Sales Forecast',
        'Menu Optimization',
        'Inventory Alert',
        'Customer Churn',
        'Employee Performance',
      ],
      required: true,
    },
    insight: {
      type: String,
      required: true,
    },
    recommendation: {
      type: String,
      default: '',
    },
    data: {
      type: mongoose.Schema.Types.Mixed,
    },
    generatedAt: {
      type: Date,
      default: Date.now,
    },
    isRead: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

export default mongoose.model('AiInsight', aiInsightSchema);
